/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        /** Update Dataset */
        patch: operations["update_dataset_api_v1_datasets__dataset_id__patch"];
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preview */
        get: operations["get_preview_api_v1_datasets__dataset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mapping */
        get: operations["get_mapping_api_v1_datasets__dataset_id__mapping_get"];
        /** Put Mapping */
        put: operations["put_mapping_api_v1_datasets__dataset_id__mapping_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profiles */
        get: operations["get_profiles_api_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_dataset_api_v1_datasets_post */
        Body_create_dataset_api_v1_datasets_post: {
            /** File */
            file: string;
            /** Industry Id */
            industry_id?: string | null;
        };
        /**
         * ColumnDisposition
         * @enum {string}
         */
        ColumnDisposition: "canonical" | "custom_dimension" | "custom_measure" | "ignored";
        /** ColumnMapping */
        ColumnMapping: {
            /** Column Key */
            column_key: string;
            /** Target Field */
            target_field?: string | null;
            disposition: components["schemas"]["ColumnDisposition"];
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** ColumnMetadata */
        ColumnMetadata: {
            /** Key */
            key: string;
            /** Original Name */
            original_name: string;
            /**
             * Detected Type
             * @default string
             */
            detected_type: string;
            /** Sample */
            sample?: (string | null)[];
            /**
             * Null Ratio
             * @default 0
             */
            null_ratio: number;
            /** Approximate Cardinality */
            approximate_cardinality?: number | null;
        };
        /** DatasetPatch */
        DatasetPatch: {
            /** Sheet */
            sheet?: string | null;
            /** Header Row */
            header_row?: number | null;
            /** Industry Id */
            industry_id?: string | null;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Stage */
            stage: string;
            /** Industry Id */
            industry_id: string | null;
            source_settings: components["schemas"]["SourceSettings"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Selected Sheet */
            selected_sheet: string | null;
            /** Available Sheets */
            available_sheets: string[];
            file: components["schemas"]["FileMetadata"] | null;
            /** Parsing Status */
            parsing_status: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnMetadata"][];
            /** Warnings */
            warnings: string[];
        };
        /** FileMetadata */
        FileMetadata: {
            /** Original Name */
            original_name: string;
            /** Extension */
            extension: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** MappingCandidate */
        MappingCandidate: {
            /** Field Id */
            field_id: string;
            /** Score */
            score: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Reasons */
            reasons: string[];
        };
        /** MappingConflict */
        MappingConflict: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Column Key */
            column_key?: string | null;
            /** Field Id */
            field_id?: string | null;
        };
        /** MappingRequest */
        MappingRequest: {
            /** Profile Id */
            profile_id: string;
            /** Mappings */
            mappings: components["schemas"]["ColumnMapping"][];
        };
        /** MappingResponse */
        MappingResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Stage */
            stage: string;
            profile: components["schemas"]["ProfileResponse"];
            /** Columns */
            columns: components["schemas"]["ColumnMetadata"][];
            /** Suggestions */
            suggestions: components["schemas"]["MappingSuggestion"][];
            /** Mappings */
            mappings: components["schemas"]["ColumnMapping"][];
            /** Conflicts */
            conflicts: components["schemas"]["MappingConflict"][];
            /** Unmapped Columns */
            unmapped_columns: string[];
        };
        /** MappingSuggestion */
        MappingSuggestion: {
            /** Column Key */
            column_key: string;
            /** Candidates */
            candidates?: components["schemas"]["MappingCandidate"][];
            suggested_disposition?: components["schemas"]["ColumnDisposition"] | null;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Max File Mb */
            max_file_mb: number;
            /** Max Rows */
            max_rows: number;
            /** Max Columns */
            max_columns: number;
            /** Ttl Minutes */
            ttl_minutes: number;
            /** Allowed Extensions */
            allowed_extensions: string[];
            /** Default Locale */
            default_locale: string;
            /** Languages */
            languages: string[];
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Selected Sheet */
            selected_sheet: string | null;
            /** Columns */
            columns: components["schemas"]["ColumnMetadata"][];
            /** Rows */
            rows: {
                [key: string]: string | null;
            }[];
            /** Warnings */
            warnings: string[];
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Fields */
            fields: components["schemas"]["PublicProfileField"][];
            /** Primary Date */
            primary_date: string;
            /** Alternate Dates */
            alternate_dates: string[];
        };
        /** ProfileSummary */
        ProfileSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** PublicProfileField */
        PublicProfileField: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Level */
            level: string;
            /** Kind */
            kind: string;
            /** Dtype */
            dtype: string;
            /** Description */
            description?: string | null;
        };
        /** SourceSettings */
        SourceSettings: {
            /** Encoding */
            encoding?: string | null;
            /** Delimiter */
            delimiter?: string | null;
            /** Sheet */
            sheet?: string | null;
            /** Header Row */
            header_row?: number | null;
            /** Decimal */
            decimal?: string | null;
            /** Thousands */
            thousands?: string | null;
            /** Date Dayfirst */
            date_dayfirst?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    create_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dataset_api_v1_datasets__dataset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preview_api_v1_datasets__dataset_id__preview_get: {
        parameters: {
            query?: {
                rows?: number | null;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mapping_api_v1_datasets__dataset_id__mapping_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_mapping_api_v1_datasets__dataset_id__mapping_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    get_profile_api_v1_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
