"""Documented noise guards for deterministic insights."""

GROWTH_MIN_ABS = 0.02
LEADER_MIN_SHARE = 0.30
LEADER_MIN_CATEGORIES = 3
CONCENTRATION_MIN_MEMBERS = 20
PEAK_MIN_PERIODS = 4
CHANNEL_MIN_CATEGORIES = 2
QUALITY_MIN_RATIO = 0.05
SUMMARY_LIMIT = 3
SECTION_LIMIT = 8
