import {test,expect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
const api="http://127.0.0.1:8100/api/v1";
async function accessible(page){expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);}
async function demo(request){const response=await request.post(`${api}/datasets/demo`,{data:{demo_id:"retail_demo"}});expect(response.status()).toBe(201);return (await response.json()).dataset_id;}
test("PLATHEL: header, metadata, columns summaries and responsive stepper",async({page,request})=>{
 const id=await demo(request);try{
 await page.goto(`/bi/${id}/mapping`);await expect(page).toHaveTitle(/PLATHEL/);await expect(page.getByRole("heading",{name:"Revisemos tus columnas"})).toBeVisible();await expect(page.getByRole("navigation",{name:"Tu progreso"}).locator('[aria-current="step"]')).toContainText("Datos");
 await expect(page.getByText(/columnas encontradas/)).toBeVisible();await expect(page.getByText(/columnas listas/)).toBeVisible();await expect(page.getByRole("combobox",{name:/Revisar columnas:/}).first()).toBeHidden();
 for(const width of [1280,768,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await accessible(page);}
 await page.getByText("Ver todas",{exact:true}).click();await expect(page.getByRole("combobox",{name:/Revisar columnas:/}).first()).toBeVisible();await expect(page.getByRole("main")).not.toContainText(/\(c0[1-9]\)|Alta confianza|DATA SIGHT/);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});
test("PLATHEL: ambiguous columns remain visible and custom dispositions stay explicit",async({page,request})=>{
 await page.goto("/bi");await page.getByLabel("Archivo de datos").setInputFiles({name:"propio.csv",mimeType:"text/csv",buffer:Buffer.from("Edad,Purchase Amount (USD)\n55,46.90\n42,48.10\n31,62.10")});await page.getByRole("button",{name:"Continuar",exact:true}).click();const link=page.getByRole("link",{name:"Revisar columnas",exact:true});const href=await link.getAttribute("href");const id=href.split('/')[2];
 try{await link.click();await expect(page.getByRole("heading",{name:"necesitan revisión",exact:true})).toBeVisible();await expect(page.getByRole("combobox",{name:"Revisar columnas: Edad",exact:true})).toBeVisible();for(const name of ["Otro dato","Valor numérico","No usar esta columna"]) expect(await page.getByRole("combobox",{name:"Revisar columnas: Edad",exact:true}).locator("option").allTextContents()).toContain(name);await accessible(page);}finally{await request.delete(`${api}/datasets/${id}`);}
});
test("PLATHEL: destructive changes require keyboard confirmation and retain observation details",async({page,request})=>{
 const id=await demo(request);const validated=await request.post(`${api}/datasets/${id}/validate`);const report=await validated.json();report.validation.issues=[];report.quality.issues=[];report.cleaning_plan.actions=[{id:"drop_exact_duplicates",description:"internal description",destructive:true,selected:false,estimated_rows_affected:2,estimated_values_affected:0,params:{}}];
 try{await page.route("**/validate",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(report)}));await page.goto(`/bi/${id}/review`);await expect(page.getByRole("heading",{name:"Preparemos tus datos"})).toBeVisible();await expect(page.getByText(/^0 observaciones/)).toHaveCount(0);const removal=page.getByRole("radio",{name:"Eliminarlas",exact:true});await expect(removal).not.toBeChecked();await removal.check();
 let cleaningRequests=0;page.on("request",req=>{if(req.url().endsWith('/cleaning') && req.method()==='PUT')cleaningRequests++;});await page.getByRole("button",{name:/Continuar (con estos|sin) ajustes/}).click();await expect(page.getByRole("dialog",{name:"Confirmar eliminación"})).toBeVisible();expect(cleaningRequests).toBe(0);await accessible(page);await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).not.toBeVisible();expect(cleaningRequests).toBe(0);await expect(page.getByRole("button",{name:/Continuar (con estos|sin) ajustes/})).toBeFocused();
 await page.getByRole("button",{name:/Continuar (con estos|sin) ajustes/}).click();await page.getByRole("button",{name:"Confirmar y preparar"}).click();await expect(page.getByRole("link",{name:"Ver resultados"})).toBeVisible();expect(cleaningRequests).toBe(1);await accessible(page);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});
test("PLATHEL: focused analysis, exploration and accessible export dialog",async({page,request})=>{
 const id=await demo(request);try{await request.post(`${api}/datasets/${id}/validate`);await request.put(`${api}/datasets/${id}/cleaning`,{data:{actions:[]}});await page.goto(`/bi/${id}/results`);await expect(page.getByRole("heading",{name:"Tu negocio, en pocas palabras",exact:true})).toBeVisible();await expect(page.getByText("Todavía no hay suficiente historial para estimar qué podría pasar después.")).toBeVisible();await expect(page.locator(".pl-kpi-grid")).toHaveCount(0);await expect(page.getByRole("heading",{name:"Gráficos clave",exact:true})).toHaveCount(0);await expect(page.getByRole("heading",{name:"Lo más importante",exact:true})).toBeVisible();await expect(page.locator(".pl-executive-findings li")).toHaveCount(3);await expect(page.getByRole("button",{name:"Exportar",exact:true})).toHaveCount(0);for(const width of [1280,390]){await page.setViewportSize({width,height:900});await accessible(page);await page.screenshot({path:`${process.env.TEMP}/plathel-results-${width}.png`,fullPage:true});}await page.getByRole("link",{name:"Explorar mis datos",exact:true}).click();await expect(page.getByRole("heading",{name:"Explorá tus datos",exact:true})).toBeVisible();await expect(page.locator("canvas").first()).toBeVisible();expect(await page.locator(".pl-kpi-grid").first().getByRole("article").count()).toBeLessThanOrEqual(5);expect(await page.locator("canvas").count()).toBeLessThanOrEqual(2);await expect(page.getByRole("button",{name:"Terminar y borrar mis datos"})).toBeHidden();await expect(page.getByRole("heading",{name:"Métricas que necesitan más información"})).toHaveCount(0);await expect(page.getByText(/Seleccioná una barra para filtrar/)).toHaveCount(0);
 const explore=page.getByRole("combobox",{name:"Ver datos por"});const options=await explore.locator("option").evaluateAll(nodes=>nodes.map(node=>({value:node.value,label:node.textContent})));await explore.selectOption(options.at(-1).value);await expect(page.locator(".pl-secondary-explorer canvas")).toBeVisible();await expect(explore).toHaveValue(options.at(-1).value);
 await expect(page.getByRole("combobox",{name:"Producto",exact:true})).toBeHidden();await page.getByText("Más filtros",{exact:true}).click();await expect(page.getByRole("combobox",{name:"Producto",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Exportar",exact:true}).click();await expect(page.getByRole("dialog",{name:"Exportar",exact:true})).toBeVisible();await expect(page.getByLabel("Encabezados de exportación")).toBeHidden();await page.getByText("Opciones avanzadas",{exact:true}).click();await expect(page.getByLabel("Encabezados de exportación")).toBeVisible();await accessible(page);await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Exportar",exact:true})).toBeFocused();
 for(const width of [1280,768,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await accessible(page);await page.screenshot({path:`${process.env.TEMP}/plathel-dashboard-${width}.png`,fullPage:true});}
 }finally{await request.delete(`${api}/datasets/${id}`);}
});

test("PLATHEL: bar selection, combined chips, keyboard removal and reset share filters",async({page,request})=>{
 const id=await demo(request);try{
 await request.post(`${api}/datasets/${id}/validate`);await request.put(`${api}/datasets/${id}/cleaning`,{data:{actions:[]}});
 const updates=[];page.on("request",request=>{if(request.url().endsWith("/dashboard")&&request.method()==="POST") updates.push(request.postDataJSON());});
 await page.goto(`/bi/${id}/dashboard`);const exploreSelect=page.getByRole("combobox",{name:"Ver datos por"});const categoryId=await exploreSelect.locator("option").filter({hasText:"Categoría"}).first().getAttribute("value");await exploreSelect.selectOption(categoryId);const category=page.getByRole("article").filter({has:page.getByRole("heading",{name:"Categoría",exact:true})});await expect(category.locator("canvas")).toBeVisible();
 const box=await category.locator("canvas").boundingBox();await category.locator("canvas").click({position:{x:box.width*.55,y:box.height*.68}});
 await expect.poll(()=>updates.at(-1)?.filters?.some(filter=>filter.field==="category")).toBe(true);await expect(page.getByRole("button",{name:"Quitar filtro Categoría",exact:true})).toBeVisible();
 await page.getByRole("combobox",{name:"Canal",exact:true}).selectOption("Online");await expect.poll(()=>updates.at(-1)?.filters?.length).toBe(2);await expect(page.getByRole("button",{name:"Quitar filtro Canal",exact:true})).toBeVisible();
 await category.getByText("Ver como tabla",{exact:true}).click();await expect(category.getByRole("button",{name:/Filtrar por/}).first()).toBeVisible();await category.getByRole("button",{name:/Filtrar por/}).first().focus();await page.keyboard.press("Enter");await expect.poll(()=>updates.at(-1)?.filters?.length).toBe(2);
 await page.getByRole("button",{name:"Quitar filtro Categoría",exact:true}).focus();await page.keyboard.press("Enter");await expect(page.getByRole("combobox",{name:"Categoría",exact:true})).toHaveValue("");await expect.poll(()=>updates.at(-1)?.filters?.length).toBe(1);
 await page.getByRole("button",{name:"Limpiar",exact:true}).click();await expect.poll(()=>updates.at(-1)?.filters?.length).toBe(0);await expect(page.getByRole("button",{name:/Quitar filtro/})).toHaveCount(0);await accessible(page);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});

test("PLATHEL: preparation hides zero impact and offers one useful decision",async({page,request})=>{
 const id=await demo(request);const report=await(await request.post(`${api}/datasets/${id}/validate`)).json();report.validation.issues=[];report.quality.issues=[];report.cleaning_plan.actions=report.cleaning_plan.actions.map(action=>({...action,estimated_rows_affected:0,estimated_values_affected:0}));
 try{await page.route("**/validate",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(report)}));await page.goto(`/bi/${id}/review`);await expect(page.getByRole("button",{name:"Continuar sin ajustes",exact:true})).toHaveCount(1);await expect(page.getByRole("checkbox")).toHaveCount(0);await expect(page.getByText("Opciones avanzadas",{exact:true})).toHaveCount(0);await expect(page.getByText(/0 filas|0 valores|Encontramos.*mejoras/)).toHaveCount(0);await accessible(page);report.cleaning_plan.actions=[{id:"trim_whitespace",selected:false,destructive:false,estimated_rows_affected:2,estimated_values_affected:2,params:{}}];await page.reload();await page.getByText("Opciones avanzadas",{exact:true}).click();await expect(page.getByRole("checkbox")).toHaveCount(1);await expect(page.getByRole("button",{name:/Continuar (con estos|sin) ajustes/})).toHaveCount(1);await accessible(page);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});
test("PLATHEL: date presets and custom dates share filtering and reset",async({page,request})=>{
 const id=await demo(request);try{await request.post(`${api}/datasets/${id}/validate`);await request.put(`${api}/datasets/${id}/cleaning`,{data:{actions:[]}});const updates=[];page.on("request",r=>{if(r.url().endsWith("/dashboard")&&r.method()==="POST")updates.push(r.postDataJSON());});await page.goto(`/bi/${id}/dashboard`);const period=page.getByRole("combobox",{name:"Fecha",exact:true});await expect(page.getByLabel("Fecha desde",{exact:true})).toHaveCount(0);await period.selectOption("3");await expect.poll(()=>updates.at(-1)?.filters?.find(f=>f.field==="date")?.values).toEqual(["2026-01-01","2026-02-21"]);await expect(page.getByRole("button",{name:"Quitar filtro Fecha",exact:true})).toBeVisible();await period.selectOption("custom");await page.getByLabel("Fecha desde",{exact:true}).fill("2026-02-01");await expect.poll(()=>updates.at(-1)?.filters?.find(f=>f.field==="date")?.values[0]).toBe("2026-02-01");await page.getByRole("button",{name:"Limpiar",exact:true}).click();await expect(period).toHaveValue("all");await expect(page.getByLabel("Fecha desde",{exact:true})).toHaveCount(0);await expect.poll(()=>updates.at(-1)?.filters?.length).toBe(0);await accessible(page);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});

test("F1: real KPI comparisons follow date range, segment and keyboard cross-filter",async({page,request})=>{
 const rows=["2025-01-01,50,30,A,ARS","2025-01-31,50,30,A,ARS","2025-01-01,200,100,B,ARS","2025-01-31,200,100,B,ARS","2025-02-01,60,33,A,ARS","2025-02-28,60,33,A,ARS","2025-02-01,50,25,B,ARS","2025-02-28,50,25,B,ARS"];
 const upload=await request.post(`${api}/datasets`,{multipart:{file:{name:"comparaciones.csv",mimeType:"text/csv",buffer:Buffer.from("fecha,importe,costo,segmento,moneda\n"+rows.join("\n"))}}});expect(upload.status()).toBe(201);const id=(await upload.json()).dataset_id;
 try{expect((await request.put(`${api}/datasets/${id}/mapping`,{data:{profile_id:"retail_ecommerce",mappings:["date","amount","cost","category","currency"].map((field,i)=>({column_key:`c${String(i+1).padStart(2,"0")}`,target_field:field,disposition:"canonical",options:field==="cost"?{basis:"total"}:{}}))}})).status()).toBe(200);await request.post(`${api}/datasets/${id}/validate`);await request.put(`${api}/datasets/${id}/cleaning`,{data:{actions:[]}});
 const kpi=name=>page.locator(".pl-kpi-grid article").filter({has:page.getByRole("heading",{name,exact:true})});await page.goto(`/bi/${id}/dashboard`);await expect(kpi("Ventas")).not.toContainText("vs. período anterior");await page.getByRole("combobox",{name:"Fecha",exact:true}).selectOption("custom");await page.getByLabel("Fecha desde",{exact:true}).fill("2025-02-01");await page.getByLabel("Fecha hasta",{exact:true}).fill("2025-02-28");await expect(kpi("Ventas")).toContainText("-56% vs. período anterior");await page.getByRole("combobox",{name:"Categoría",exact:true}).selectOption("A");await expect(kpi("Ventas")).toContainText("+20% vs. período anterior");await expect(page.locator(".pl-executive-findings")).toContainText("Venta aumentó 20,0 % respecto del período anterior");await expect(kpi("Margen bruto")).toContainText("+5 puntos porcentuales");await expect(kpi("Ventas").locator("[title*=\"Período actual\"]")).toHaveAttribute("title",/2025-01-01 a 2025-01-31/);
 await page.getByRole("button",{name:"Quitar filtro Categoría",exact:true}).click();await expect(kpi("Ventas")).toContainText("-56% vs. período anterior");await page.getByRole("combobox",{name:"Ver datos por",exact:true}).selectOption({label:"Categoría"});const explorer=page.locator(".pl-secondary-explorer");await explorer.getByText("Ver como tabla",{exact:true}).click();await explorer.getByRole("button",{name:"Filtrar por A",exact:true}).focus();await page.keyboard.press("Enter");await expect(kpi("Ventas")).toContainText("+20% vs. período anterior");await page.getByRole("button",{name:"Limpiar",exact:true}).click();await expect(kpi("Ventas")).not.toContainText("vs. período anterior");for(const width of [1280,390]){await page.setViewportSize({width,height:900});await accessible(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 }finally{await request.delete(`${api}/datasets/${id}`);}
});

test("F3: robust anomaly follows the active business filter",async({page,request})=>{
 const normal=[100,101,99,102,98,100,101,99,100,102,98,300];const rows=[];
 for(let month=1;month<=12;month++){const day=new Date(Date.UTC(2024,month,0)).getUTCDate();const stamp=`2024-${String(month).padStart(2,"0")}-${day}`;rows.push(`${stamp},${normal[month-1]},A,ARS`);rows.push(`${stamp},50,B,ARS`);}
 const upload=await request.post(`${api}/datasets`,{multipart:{file:{name:"anomalias.csv",mimeType:"text/csv",buffer:Buffer.from("fecha,importe,categoria,moneda\n"+rows.join("\n"))}}});expect(upload.status()).toBe(201);const id=(await upload.json()).dataset_id;
 try{expect((await request.put(`${api}/datasets/${id}/mapping`,{data:{profile_id:"retail_ecommerce",mappings:["date","amount","category","currency"].map((field,i)=>({column_key:`c${String(i+1).padStart(2,"0")}`,target_field:field,disposition:"canonical",options:{}}))}})).status()).toBe(200);await request.post(`${api}/datasets/${id}/validate`);await request.put(`${api}/datasets/${id}/cleaning`,{data:{actions:[]}});await page.goto(`/bi/${id}/dashboard`);const retry=page.getByRole("button",{name:"Reintentar"});if(await retry.isVisible())await retry.click();await expect(page.locator(".pl-executive-findings")).toContainText("inusualmente alto");const category=page.getByRole("combobox",{name:"Categoría",exact:true});await Promise.all([page.waitForResponse(r=>r.url().endsWith("/dashboard")&&r.request().method()==="POST"),category.selectOption("B")]);await expect(page.getByText(/inusualmente alto/)).toHaveCount(0);await Promise.all([page.waitForResponse(r=>r.url().endsWith("/dashboard")&&r.request().method()==="POST"),category.selectOption("A")]);await expect(page.locator(".pl-executive-findings")).toContainText("inusualmente alto");await accessible(page);
 }finally{await request.delete(`${api}/datasets/${id}`);}
});
