"use client";
import {ForecastWorkspace} from "@/forecast/workspace";
import { t } from "@/lib/i18n";
import { fieldLabel } from "@/lib/presentation";
import { useEffect, useState } from "react";
import { ExportControls } from "./export-controls";
import { DemoNotice } from "./demo-notice";
import { DashboardRenderer } from "./dashboard-renderer";
import { Button, Input, Select, ErrorState, LoadingState } from "@/components/ui/primitives";
import { DashboardResponse, FilterClause, getDashboard, getFilterOptions } from "@/lib/api/dashboard";
export function DashboardPage({datasetId,mode="dashboard"}:{datasetId:string;mode?:"results"|"dashboard"}){
 const [dashboard,setDashboard]=useState<DashboardResponse|null>(null);const [filters,setFilters]=useState<FilterClause[]>([]);const [displayedFilters,setDisplayedFilters]=useState<FilterClause[]|null>(null);const [searchOptions,setSearchOptions]=useState<Record<string,string[]>>({});const [error,setError]=useState("");const [searchError,setSearchError]=useState("");
 useEffect(()=>{let active=true;getDashboard(datasetId,{filters,comparison:{mode:"previous_period"},grain:"auto"}).then(result=>{if(active){setDashboard(result);setDisplayedFilters(filters);setError("");}}).catch(()=>{if(active)setError(t("product.filterError"));});return ()=>{active=false;};},[datasetId,filters]);
 const retry=()=>{setError("");setFilters(current=>[...current]);};
 if(!dashboard)return error ? <ErrorState message={error} onRetry={retry}/> : <LoadingState/>;
 function replaceFilter(field:string,next?:FilterClause){setError("");setFilters(current=>[...current.filter(item=>item.field!==field),...(next?[next]:[])]);}
 function datePart(field:string,index:number,value:string,minimum?:string|null,maximum?:string|null){if(!value){replaceFilter(field);return;}const existing=filters.find(item=>item.field===field && item.op==="between");const values=existing?.values.map(String) ?? [minimum ?? value,maximum ?? value];values[index]=value;if(values[0] && values[1])replaceFilter(field,{field,op:"between",values});}
 const definitions=dashboard.spec.filters;const firstDate=definitions.find(filter=>filter.type==="date_range");const primary=definitions.filter(filter=>filter===firstDate || ["currency","channel"].includes(filter.field));if(primary.length<3){for(const filter of definitions){if(primary.length>=3)break;if(!primary.includes(filter) && filter.type!=="date_range")primary.push(filter);}}
 const secondary=definitions.filter(filter=>!primary.includes(filter));const terminology=dashboard.spec.terminology ?? {};
 function control(filter:DashboardResponse["spec"]["filters"][number]){const label=terminology[filter.field] ?? t(filter.label_key);const selected=filters.find(item=>item.field===filter.field);return <div key={filter.id} className="pl-filter-control">{filter.type==="date_range" ? <><span>{label}</span><div className="pl-filter-dates"><Input aria-label={`${label} ${t("product.dateFrom")}`} type="date" min={filter.minimum ?? undefined} max={filter.maximum ?? undefined} value={selected ? String(selected.values[0] ?? "") : ""} onChange={event=>datePart(filter.field,0,event.target.value,filter.minimum,filter.maximum)}/><Input aria-label={`${label} ${t("product.dateTo")}`} type="date" min={filter.minimum ?? undefined} max={filter.maximum ?? undefined} value={selected ? String(selected.values[1] ?? "") : ""} onChange={event=>datePart(filter.field,1,event.target.value,filter.minimum,filter.maximum)}/></div></> : filter.type==="search" ? <label>{label}<Input aria-label={`${t("product.search")} ${label}`} list={`options-${filter.id}`} placeholder={`${t("product.search")} ${label}`} value={String(selected?.values[0] ?? "")} onChange={event=>{const value=event.target.value;replaceFilter(filter.field,value?{field:filter.field,op:"contains",values:[value]}:undefined);setSearchError("");if(value.length>=2)getFilterOptions(datasetId,filter.field,value).then(result=>setSearchOptions(current=>({...current,[filter.field]:result.options.map(item=>item.value)}))).catch(()=>setSearchError(t("request.failed")));}}/><datalist id={`options-${filter.id}`}>{(searchOptions[filter.field] ?? []).map(value=><option key={value} value={value}/>)}</datalist></label> : <label>{label}<Select aria-label={label} value={String(selected?.values[0] ?? "")} onChange={event=>replaceFilter(filter.field,event.target.value?{field:filter.field,op:"in",values:[event.target.value]}:undefined)}><option value="">{t("product.allFilters")}</option>{filter.options?.map(option=><option key={option.value} value={option.value}>{option.value} ({option.count})</option>)}</Select></label>}</div>;}
 return <div><DemoNotice datasetId={datasetId}/><div className="pl-page-heading"><p className="pl-analysis-meta">{dashboard.filtered_row_count}{t("dashboard-page.text2")}{dashboard.row_count}{t("dashboard-page.text3")}</p><p className="home-eyebrow">{mode==="results"?"02 / RESULTADOS + PREDICCIONES":"03 / DASHBOARD"}</p><h1>{mode==="results"?"Esto es lo que encontramos":t("product.analysis")}</h1><p>{mode==="results"?"Un resumen de tus datos y de lo que podemos estimar.":"Usá los filtros para descubrir lo que te interesa."}</p></div>
 {mode==="dashboard" && <details open className="pl-details pl-filters"><summary>{t("filters.title")}</summary><div className="pl-filter-fields">{primary.map(control)}</div>{secondary.length>0 && <details className="pl-details mt-5"><summary>{t("product.moreFilters")}</summary><div className="pl-filter-fields">{secondary.map(control)}</div></details>}{filters.length>0 && <Button className="mt-3" variant="ghost" onClick={()=>{setError("");setFilters([]);}}>{t("product.resetFilters")}</Button>}</details>}
 <p role="status" className="sr-only">{error?"":displayedFilters!==filters?t("dashboard.loading"):`${dashboard.filtered_row_count} ${t("product.filteredRows")}`}</p>{error && <ErrorState message={error} onRetry={retry}/>} {searchError && <ErrorState message={searchError}/>}
 <DashboardRenderer dashboard={dashboard} mode={mode}/>{mode==="results" && <><ForecastWorkspace datasetId={datasetId} embedded/><div className="pl-actions"><a className="pl-button pl-button--primary" href={`/bi/${datasetId}/dashboard`}>Explorar dashboard</a></div></>}{mode==="dashboard" && dashboard.spec.unavailable_metrics.length>0 && <details className="pl-details"><summary>{t("product.unavailable")} ({dashboard.spec.unavailable_metrics.length})</summary><ul>{dashboard.spec.unavailable_metrics.map(metric=><li className="pl-observation" key={metric.metric_id}><strong>{t(metric.label_key ?? `metric.${metric.metric_id}`)}</strong><p>{metric.missing_fields.length ? `${t("product.metricNeeds")} ${metric.missing_fields.map(field=>fieldLabel(field,terminology)).join(", ")}.` : metric.reason_key==="metric.requires_cost_basis_total" ? t("product.costBasis") : metric.reason_key==="metric.requires_discount_kind_amount" ? t("product.discountKind") : t("product.compatibleContext")}</p></li>)}</ul></details>}
 {mode==="dashboard" && <section className="pl-dashboard-section"><ExportControls datasetId={datasetId} filters={displayedFilters ?? []} disabled={displayedFilters!==filters}/></section>}
 </div>;
}
