"use client";
import { useState, type CSSProperties } from "react";
import type { components } from "@/types/api.generated";
import { EChartsBase } from "@/components/charts/echarts-base";
import { chartOption } from "@/components/charts/adapters/dashboard";
import { messages as labels, t, insightText } from "@/lib/i18n";
import { fieldLabel, humanMessage } from "@/lib/presentation";
import { EmptyState, ErrorState, Select } from "@/components/ui/primitives";
export { EmptyState, ErrorState } from "@/components/ui/primitives";
type DashboardResponse=components["schemas"]["DashboardResponse"];type Widget=components["schemas"]["WidgetSpec"];type Metric=components["schemas"]["MetricResult"];type Chart=components["schemas"]["ChartResult"];type Quality=components["schemas"]["QualityResult"];
function title(key:string,terminology:Record<string,string>){if(key==="metric.revenue"&&terminology.amount)return terminology.amount==="Venta"?"Ventas":terminology.amount==="Ingreso"?"Ingresos":terminology.amount==="Importe"?"Importe total":terminology.amount;if(key==="metric.avg_transaction_value"&&terminology.amount!=="Venta")return "Importe promedio por operación";if(key.startsWith("custom__"))return fieldLabel(key,terminology);return key.startsWith("field.") ? fieldLabel(key.slice(6),terminology) : labels[key] ?? t("product.otherData");}
function metricValue(metric:Metric){return metric.value==null ? "—" : new Intl.NumberFormat("es-AR",{style:metric.format.type==="currency"?"currency":metric.format.type==="percent"?"percent":"decimal",currency:metric.format.currency ?? "ARS",minimumFractionDigits:0,maximumFractionDigits:metric.format.decimals}).format(metric.value);}
function ComparisonNote({metric}:{metric:Metric}){const c=metric.comparison;if(!c||!["ok","previous_zero"].includes(c.status))return null;const signed=(value:number,type:"percent"|"decimal")=>new Intl.NumberFormat("es-AR",{style:type,maximumFractionDigits:type==="percent"?1:2,signDisplay:"exceptZero"}).format(value);const change=c.delta_pp!=null?`${signed(c.delta_pp,"decimal")} puntos porcentuales`:c.delta_pct!=null?signed(c.delta_pct,"percent"):c.delta_abs!=null?new Intl.NumberFormat("es-AR",{style:metric.format.type==="currency"?"currency":"decimal",currency:metric.format.currency??"ARS",maximumFractionDigits:metric.format.decimals,signDisplay:"exceptZero"}).format(c.delta_abs):null;if(change==null)return null;const range=(value:components["schemas"]["DateRange"]|null|undefined)=>value?`${value.from} a ${value.to}`:"";const context=`Período actual: ${range(c.current_range)}. Período anterior: ${range(c.previous_range)}. Valor anterior: ${metricValue({...metric,value:c.previous_value})}.`;return <span title={context}><span aria-hidden="true">{c.direction==="increase"?"↑ ":c.direction==="decrease"?"↓ ":""}</span>{change} vs. período anterior{c.warnings?.some(w=>w.code==="PARTIAL_PREVIOUS_PERIOD")?" (período anterior parcialmente cubierto)":""}{c.partial_period?" (período actual incompleto)":""}</span>;}
function WidgetView({widget,value,label,onSelect,selected=[]}:{widget:Widget;value:unknown;label:string;onSelect?:(index:number)=>void;selected?:string[]}){
 const base=value as {status?:string}|undefined;if(!base || base.status==="empty" || base.status==="unavailable")return <EmptyState/>;if(base.status==="error")return <ErrorState/>;
 if(widget.type==="kpi"){const metric=value as Metric;return <div><p className="pl-kpi-value">{metricValue(metric)}</p>{metric.comparison&&["ok","previous_zero"].includes(metric.comparison.status)&&<p className="pl-comparison"><ComparisonNote metric={metric}/></p>}{metric.excluded_rows>0 && <details className="mt-3 text-xs"><summary>{metric.excluded_rows}{t("dashboard-renderer.text2")}</summary><p>{t("product.metricNeeds")}</p></details>}</div>;}
 if(["timeseries","breakdown","ranking"].includes(widget.type)){const chart=value as Chart;return <><EChartsBase onSelect={onSelect?event=>onSelect(event.dataIndex):undefined} label={label} option={chartOption(chart,t(chart.series?.[0]?.label_key ?? "chart.value"),selected)}/><details className="pl-details"><summary>{t("chart.table")}</summary><div className="overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">{label}</caption><thead><tr><th scope="col">{t("chart.category")}</th><th scope="col">{t("chart.value")}</th></tr></thead><tbody>{(chart.series ?? []).flatMap(series=>series.points.map((point,i)=><tr key={`${series.key}-${i}`}><th scope="row">{onSelect && !(chart.meta?.has_others_bucket && point[0]==="Otros")?<button className="pl-chart-filter" aria-pressed={selected.includes(String(point[0]))} onClick={()=>onSelect(i)} aria-label={`Filtrar por ${String(point[0])}`}>{String(point[0])}</button>:String(point[0])}</th><td>{typeof point[1]==="number"?new Intl.NumberFormat("es-AR").format(point[1]):String(point[1] ?? "—")}</td></tr>))}</tbody></table></div></details></>;}
 if(widget.type==="quality"){const q=value as Quality;return <div><p>{q.total_issues===0?t("product.qualityReady"):`${q.total_issues} ${t("product.observations")}`}</p><details className="pl-details"><summary>{t("product.details")}</summary><p>{q.error_count}{t("dashboard-renderer.text5")}{q.warning_count}{t("dashboard-renderer.text6")}</p></details></div>;}
 return <ErrorState/>;
}
function insightCopy(item:components["schemas"]["Insight"],terminology:Record<string,string>){return item.template_key.startsWith("insight.")?insightText(item.template_key,item.params):humanMessage(item.text,terminology);}
function insightIdentity(item:components["schemas"]["Insight"]){const p=item.params;return item.template_key.includes("peak_period")?`peak:${p.period}:${p.value}`:["insight.leader_share","insight.industry_leader","insight.channel_dominance"].includes(item.template_key)?`leader:${(item.dimension??"").replace("field.","")}:${p.value??p.channel}:${p.share}`:`${item.template_key}:${JSON.stringify(p)}`;}
export function DashboardRenderer({dashboard,mode="dashboard",onFilter,filters=[]}:{dashboard:DashboardResponse;mode?:"results"|"dashboard";onFilter?:(field:string,value:string)=>void;filters?:components["schemas"]["FilterClause"][]}){
 const [exploreId,setExploreId]=useState("");const terminology=dashboard.spec.terminology??{};const all=[...new Map(dashboard.spec.sections.flatMap(section=>section.widgets).map(widget=>[widget.id,widget])).values()];
 const available=(widget:Widget)=>(dashboard.data[widget.id] as {status?:string}|undefined)?.status==="ok";
 const kpis=all.filter(widget=>widget.type==="kpi"&&available(widget));const main=all.find(widget=>widget.type==="timeseries"&&available(widget));
 const field=(widget:Widget)=>{const dimension=(dashboard.data[widget.id] as Chart)?.meta?.dimension;return typeof dimension==="string"?dimension:widget.title_key.startsWith("field.")?widget.title_key.slice(6):widget.title_key.startsWith("custom__")?widget.title_key:"";};
 const seen=new Set<string>();const charts=all.filter(widget=>["breakdown","ranking"].includes(widget.type)&&available(widget)).filter(widget=>{const key=field(widget)||widget.id;if(seen.has(key))return false;seen.add(key);return true;});
 const explore=charts.find(widget=>widget.id===exploreId)??charts.find(widget=>widget.id===dashboard.spec.key_chart_ids?.[1])??charts[0];
 const local=[main,explore].filter((widget):widget is Widget=>Boolean(widget)).map(widget=>(dashboard.data[widget.id] as Chart).interpretation).filter((item):item is components["schemas"]["Insight"]=>Boolean(item));const shown=new Set(mode==="dashboard"?local.map(insightIdentity):[]);
 const findings=all.filter(widget=>widget.type==="insights").flatMap(widget=>(dashboard.data[widget.id] as {insights?:components["schemas"]["Insight"][]}|undefined)?.insights??[]).filter(item=>{const key=insightIdentity(item);if(shown.has(key))return false;shown.add(key);return true;});
 function chart(widget:Widget){const result=dashboard.data[widget.id] as Chart;const dimension=field(widget);const definition=dashboard.spec.filters?.find(item=>item.field===dimension);const selected=filters.find(filter=>filter.field===dimension)?.values.map(String)??[];
 const select=onFilter&&definition&&widget.type!=="timeseries"?(index:number)=>{const value=result.series?.[0]?.points[index]?.[0];if(value!=null&&!(result.meta?.has_others_bucket&&value==="Otros"))onFilter(dimension,String(value));}:undefined;
 return <article className="pl-chart" key={widget.id} data-interactive={Boolean(select)} title={select?"Seleccionar para filtrar":undefined}><h3>{title(widget.title_key,terminology)}</h3><WidgetView widget={widget} value={result} selected={selected} onSelect={select} label={title(widget.title_key,terminology)}/>{result.interpretation&&<div className="pl-chart-interpretation"><h4>Qué significa</h4><p>{insightCopy(result.interpretation,terminology)}</p></div>}</article>;}
 const quality=all.filter(widget=>widget.type==="quality");const unavailable=dashboard.spec.unavailable_metrics??[];const extra=kpis.slice(5);const unknown=all.filter(widget=>!['kpi','timeseries','breakdown','ranking','insights','quality'].includes(widget.type));
 const summary=kpis.slice(0,1);const second=kpis.find(widget=>widget.title_key==="metric.gross_margin_pct")??kpis[1];if(second&&!summary.includes(second))summary.push(second);
 return <div className={`pl-dashboard ${mode==="results"?"pl-executive-reading":""}`}>
 {mode==="results"?summary.length>0&&<p className="pl-executive-summary">{summary.map((widget,index)=><span key={widget.id}>{widget.title_key==="metric.revenue"?<>Durante el período analizado registraste <strong>{metricValue(dashboard.data[widget.id] as Metric)}</strong> en {title(widget.title_key,terminology).toLowerCase()}.</>:widget.title_key==="metric.gross_margin_pct"?<> Tu margen bruto fue de <strong>{metricValue(dashboard.data[widget.id] as Metric)}</strong>.</>:<>{index===0?"Durante el período analizado, ":" "}{index===0?title(widget.title_key,terminology).toLowerCase():title(widget.title_key,terminology)}: <strong>{metricValue(dashboard.data[widget.id] as Metric)}</strong>.</>}<span className="pl-comparison"> <ComparisonNote metric={dashboard.data[widget.id] as Metric}/></span></span>)}</p>:kpis.length>0&&<section className="pl-dashboard-section pl-summary"><h2 className="sr-only">Resumen</h2><div className="pl-kpi-grid">{kpis.slice(0,5).map(widget=><article key={widget.id} className="dashboard-widget pl-kpi" style={{"--widget-span":widget.layout.span} as CSSProperties}><h3>{title(widget.title_key,terminology)}</h3><WidgetView widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/></article>)}</div></section>}
 {mode==="dashboard"&&main&&<section className="pl-dashboard-section"><h2>Evolución</h2><div className="pl-key-charts">{chart(main)}</div></section>}
 {findings.length>0&&<section className="pl-dashboard-section"><h2>{mode==="results"?"Lo más importante":"Hallazgos"}</h2><ul className="pl-findings pl-executive-findings">{findings.slice(0,3).map(item=><li key={item.id}>{insightCopy(item,terminology)}</li>)}</ul>{mode==="dashboard"&&findings.length>3&&<details className="pl-details"><summary>Ver más</summary><ul className="pl-findings">{findings.slice(3).map(item=><li key={item.id}>{insightCopy(item,terminology)}</li>)}</ul></details>}</section>}
 {mode==="dashboard"&&explore&&<section className="pl-dashboard-section"><h2>Explorar</h2><div className="pl-secondary-explorer"><label className="pl-explore-label">Ver datos por<Select aria-label="Ver datos por" value={explore.id} onChange={event=>setExploreId(event.target.value)}>{charts.map(widget=><option key={widget.id} value={widget.id}>{field(widget)?fieldLabel(field(widget),terminology):title(widget.title_key,terminology)}</option>)}</Select></label>{chart(explore)}</div></section>}
 {mode==="dashboard"&&(quality.length>0||unavailable.length>0||extra.length>0||unknown.length>0)&&<details className="pl-details pl-about-data"><summary>Sobre estos datos</summary>{quality.map(widget=><WidgetView key={widget.id} widget={widget} value={dashboard.data[widget.id]} label="Calidad"/>)}{extra.length>0&&<details><summary>Más indicadores</summary><ul>{extra.map(widget=><li key={widget.id}>{title(widget.title_key,terminology)}: {metricValue(dashboard.data[widget.id] as Metric)}</li>)}</ul></details>}{unavailable.length>0&&<details><summary>Información disponible y limitaciones</summary><ul>{unavailable.map(metric=><li key={metric.metric_id}>{t(metric.label_key??`metric.${metric.metric_id}`)}: {metric.missing_fields.map(value=>fieldLabel(value,terminology)).join(", ")||"Requiere información adicional"}.</li>)}</ul></details>}{unknown.map(widget=><WidgetView key={widget.id} widget={widget} value={dashboard.data[widget.id]} label="Información del análisis"/>)}</details>}
 {all.some(widget=>(dashboard.data[widget.id] as {status?:string}|undefined)?.status==="error")&&<ErrorState/>}
 </div>;
}
