"use client";
import { useState, type CSSProperties } from "react";
import type { components } from "@/types/api.generated";
import { EChartsBase } from "@/components/charts/echarts-base";
import { chartOption } from "@/components/charts/adapters/dashboard";
import { messages as labels, t, insightText } from "@/lib/i18n";
import { fieldLabel, humanMessage } from "@/lib/presentation";
import { EmptyState, ErrorState, Select } from "@/components/ui/primitives";
export { EmptyState, ErrorState } from "@/components/ui/primitives";
type DashboardResponse=components["schemas"]["DashboardResponse"];type Widget=components["schemas"]["WidgetSpec"];type Metric=components["schemas"]["MetricResult"];type Chart=components["schemas"]["ChartResult"];type Quality=components["schemas"]["QualityResult"];
function title(key:string,terminology:Record<string,string>){return key.startsWith("field.") ? fieldLabel(key.slice(6),terminology) : labels[key] ?? t("product.otherData");}
function metricValue(metric:Metric){return metric.value==null ? "—" : new Intl.NumberFormat("es-AR",{style:metric.format.type==="currency"?"currency":metric.format.type==="percent"?"percent":"decimal",currency:metric.format.currency ?? "ARS",maximumFractionDigits:metric.format.decimals}).format(metric.value);}
function WidgetView({widget,value,label}:{widget:Widget;value:unknown;label:string}){
 const base=value as {status?:string}|undefined;if(!base || base.status==="empty" || base.status==="unavailable")return <EmptyState/>;if(base.status==="error")return <ErrorState/>;
 if(widget.type==="kpi"){const metric=value as Metric;const delta=metric.comparison?.delta_pct;return <div><p className="pl-kpi-value">{metricValue(metric)}</p>{delta!=null && <p className="pl-comparison"><span aria-hidden="true">{delta>0?"↑":delta<0?"↓":"="} </span>{new Intl.NumberFormat("es-AR",{style:"percent",maximumFractionDigits:1,signDisplay:"exceptZero"}).format(delta)}{t("dashboard-renderer.text3")}</p>}{metric.excluded_rows>0 && <details className="mt-3 text-xs"><summary>{metric.excluded_rows}{t("dashboard-renderer.text2")}</summary><p>{t("product.metricNeeds")}</p></details>}</div>;}
 if(["timeseries","breakdown","ranking"].includes(widget.type)){const chart=value as Chart;return <><EChartsBase label={label} option={chartOption(chart,t(chart.series?.[0]?.label_key ?? "chart.value"))}/><details className="pl-details"><summary>{t("chart.table")}</summary><div className="overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">{label}</caption><thead><tr><th scope="col">{t("chart.category")}</th><th scope="col">{t("chart.value")}</th></tr></thead><tbody>{(chart.series ?? []).flatMap(series=>series.points.map((point,i)=><tr key={`${series.key}-${i}`}><th scope="row">{String(point[0])}</th><td>{typeof point[1]==="number"?new Intl.NumberFormat("es-AR").format(point[1]):String(point[1] ?? "—")}</td></tr>))}</tbody></table></div></details></>;}
 if(widget.type==="quality"){const q=value as Quality;return <div><p>{q.total_issues===0?t("product.qualityReady"):`${q.total_issues} ${t("product.observations")}`}</p><details className="pl-details"><summary>{t("product.details")}</summary><p>{q.error_count}{t("dashboard-renderer.text5")}{q.warning_count}{t("dashboard-renderer.text6")}</p></details></div>;}
 return <ErrorState/>;
}
export function DashboardRenderer({dashboard}:{dashboard:DashboardResponse}){
 const [exploreId,setExploreId]=useState("");const terminology=dashboard.spec.terminology ?? {};const all=dashboard.spec.sections.flatMap(section=>section.widgets);const available=(widget:Widget)=>!['unavailable'].includes((dashboard.data[widget.id] as {status?:string}|undefined)?.status ?? "");const kpis=all.filter(widget=>widget.type==="kpi" && available(widget));const mainChart=all.find(widget=>widget.type==="timeseries" && available(widget));const charts=all.filter(widget=>["timeseries","breakdown","ranking"].includes(widget.type) && widget!==mainChart && available(widget));const explore=charts.find(widget=>widget.id===exploreId) ?? charts[0];const quality=all.filter(widget=>widget.type==="quality");const other=all.filter(widget=>!['kpi','timeseries','breakdown','ranking','insights','quality'].includes(widget.type));
 const findings=all.filter(widget=>widget.type==="insights").flatMap(widget=>(dashboard.data[widget.id] as {insights?:components["schemas"]["Insight"][]}|undefined)?.insights ?? []);
 const insight=(item:components["schemas"]["Insight"])=> <li key={item.id}>{item.template_key.startsWith("insight.") ? insightText(item.template_key,item.params) : humanMessage(item.text,terminology)}</li>;
 function chart(widget:Widget){return <article className="pl-chart" key={widget.id}><h3>{title(widget.title_key,terminology)}</h3><WidgetView widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/></article>;}
 return <div className="pl-dashboard"><section className="pl-dashboard-section"><h2>{t("product.summary")}</h2>{kpis.length ? <div className="pl-kpi-grid">{kpis.slice(0,6).map(widget=><article key={widget.id} className="dashboard-widget pl-kpi" style={{"--widget-span":widget.layout.span} as CSSProperties}><h3>{title(widget.title_key,terminology)}</h3><WidgetView widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/></article>)}</div> : <EmptyState/>}{kpis.length>6 && <details className="pl-details"><summary>{t("product.moreMetrics")}</summary><div className="pl-kpi-grid">{kpis.slice(6).map(widget=><article key={widget.id} className="dashboard-widget pl-kpi"><h3>{title(widget.title_key,terminology)}</h3><WidgetView widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/></article>)}</div></details>}</section>
 {mainChart && <section className="pl-dashboard-section"><h2>{t("product.evolution")}</h2>{chart(mainChart)}</section>}
 {findings.length>0 && <section className="pl-dashboard-section"><h2>{t("product.findings")}</h2><ul className="pl-findings">{findings.slice(0,3).map(insight)}</ul>{findings.length>3 && <details className="pl-details"><summary>{t("product.moreFindings")}</summary><ul className="pl-findings">{findings.slice(3).map(insight)}</ul></details>}</section>}
 {explore && <section className="pl-dashboard-section"><h2>{t("product.explore")}</h2><label className="pl-explore-label">{t("product.exploreSelect")}<Select aria-label={t("product.exploreSelect")} value={explore.id} onChange={event=>setExploreId(event.target.value)}>{charts.map(widget=><option key={widget.id} value={widget.id}>{title(widget.title_key,terminology)}</option>)}</Select></label>{chart(explore)}</section>}
 {(quality.length>0 || other.length>0) && <section className="pl-dashboard-section"><h2>{t("product.quality")}</h2>{quality.map(widget=><WidgetView key={widget.id} widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/>)}{other.map(widget=><WidgetView key={widget.id} widget={widget} value={dashboard.data[widget.id]} label={title(widget.title_key,terminology)}/>)}</section>}
 </div>;
}
