"use client";
import { t } from "@/lib/i18n";
import { useState } from "react";
import type { FilterClause } from "@/lib/api/dashboard";
import { downloadDataset, ExportOptions } from "@/lib/api/exports";
import { Button, Select, Dialog } from "@/components/ui/primitives";
export function ExportControls({datasetId,filters,disabled=false}:{datasetId:string;filters:FilterClause[];disabled?:boolean}){
 const [open,setOpen]=useState(false);const [format,setFormat]=useState("csv");const [scope,setScope]=useState<ExportOptions["scope"]>("filtered_data");const [headers,setHeaders]=useState<ExportOptions["headers"]>("friendly");const [original,setOriginal]=useState(false);const [ignored,setIgnored]=useState(false);const [transformations,setTransformations]=useState(true);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const [failed,setFailed]=useState(false);
 async function download(){if(busy || disabled)return;setBusy(true);setFailed(false);setStatus(t("export-controls.text1"));try{await downloadDataset(datasetId,{format,scope,headers,filters:scope==="filtered_data"?filters:[],include_original_columns:original,include_ignored_columns:ignored,include_transformations:transformations});setStatus(t("export-controls.text2"));}catch{setFailed(true);setStatus(t("export-controls.text3"));}finally{setBusy(false);}}
 return <><Button variant="secondary" onClick={()=>setOpen(true)}>{t("export-controls.action3")}</Button><Dialog open={open} onClose={()=>setOpen(false)} title={t("export-controls.action3")}><p className="mb-6 text-sm text-slate-600">{t("product.exportIntro")}</p><div className="pl-export-fields"><label>{t("export-controls.text4")}<Select aria-label={t("export-controls.text5")} value={format} onChange={event=>setFormat(event.target.value)}><option value="csv">{t("export-controls.text6")}</option><option value="xlsx">{t("product.excel")}</option></Select></label><label>{t("export-controls.text8")}<Select aria-label={t("export-controls.text9")} value={scope} onChange={event=>setScope(event.target.value as ExportOptions["scope"])}><option value="clean_data">{t("product.fullData")}</option><option value="filtered_data">{t("export-controls.text11")}</option></Select></label></div><details className="pl-details mt-6"><summary>{t("product.advanced")}</summary><div className="pl-export-fields"><label>{t("export-controls.text12")}<Select aria-label={t("export-controls.text13")} value={headers} onChange={event=>setHeaders(event.target.value as ExportOptions["headers"])}><option value="friendly">{t("export-controls.text14")}</option><option value="original">{t("export-controls.text15")}</option></Select></label></div><div className="pl-export-options"><label><input type="checkbox" checked={original} onChange={event=>setOriginal(event.target.checked)}/>{t("export-controls.text16")}</label><label><input type="checkbox" checked={ignored} onChange={event=>setIgnored(event.target.checked)}/>{t("export-controls.text17")}</label><label><input type="checkbox" disabled={format!=="xlsx"} checked={transformations} onChange={event=>setTransformations(event.target.checked)}/>{t("export-controls.text18")}</label></div></details><div className="pl-actions"><Button busy={busy} onClick={download} disabled={disabled}>{busy?t("export-controls.action2"):t("export-controls.action1")}</Button></div><p role={failed?"alert":"status"} className="mt-4 text-sm">{disabled?t("export-controls.text19"):status}</p></Dialog></>;
}
